version: '3.9'

services:
  angular-app:
    container_name: angular-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - angular
  json-server:
    image: clue/json-server
    ports:
      - "3000:3000"
    volumes:
      - ./json-server/db.json:/data/db.json

networks:
  angular:
    driver: bridge